### Create a new user
POST http://localhost:5268/register
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd"
}

### Log in the user
POST http://localhost:5268/login?useCookies=true
Content-Type: application/json

{
    "email": "testuser@example.com",
    "password": "P@ssw0rd"
}

### Access unprotected route
GET http://localhost:5268/

### Access the protected route
GET http://localhost:5268/protected